"""first migration

Revision ID: a5978380539e
Revises: 
Create Date: 2025-07-15 13:16:29.801828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5978380539e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_levels_id'), 'education_levels', ['id'], unique=False)
    op.create_table('employment_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_statuses_id'), 'employment_statuses', ['id'], unique=False)
    op.create_table('relationship_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_statuses_id'), 'relationship_statuses', ['id'], unique=False)
    op.create_table('soc_dem_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('workclass_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('education_num', sa.Integer(), nullable=True),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('capital_gain', sa.Integer(), nullable=True),
    sa.Column('capital_loss', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('was_used_for_training', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], ['education_levels.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship_statuses.id'], ),
    sa.ForeignKeyConstraint(['workclass_id'], ['employment_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soc_dem_profiles_id'), 'soc_dem_profiles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soc_dem_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['soc_dem_profile_id'], ['soc_dem_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_soc_dem_profiles_id'), table_name='soc_dem_profiles')
    op.drop_table('soc_dem_profiles')
    op.drop_index(op.f('ix_relationship_statuses_id'), table_name='relationship_statuses')
    op.drop_table('relationship_statuses')
    op.drop_index(op.f('ix_employment_statuses_id'), table_name='employment_statuses')
    op.drop_table('employment_statuses')
    op.drop_index(op.f('ix_education_levels_id'), table_name='education_levels')
    op.drop_table('education_levels')
    # ### end Alembic commands ###
